"""Article Generator - Orchestrates 12-section article generation

Each section is generated by a template generator in generators/templates/.
Uses stock code + date as seed for deterministic randomness.
"""

import json
import logging
import random
from datetime import date
from typing import Optional

from generators.templates.dragon_tiger import generate_dragon_tiger
from generators.templates.abnormal_change import generate_abnormal_change
from generators.templates.sector_correlation import generate_sector_correlation
from generators.templates.fundamentals import generate_fundamentals
from generators.templates.business_analysis import generate_business_analysis
from generators.templates.subsidiaries import generate_subsidiaries
from generators.templates.technical import generate_technical
from generators.templates.fund_flow import generate_fund_flow
from generators.templates.institutional import generate_institutional
from generators.templates.announcements import generate_announcements
from generators.templates.risk_warning import generate_risk_warning
from generators.templates.ai_rating import generate_ai_rating

logger = logging.getLogger("stock-analysis.generator")


def generate_article(
    stock: dict,
    snapshot_date: str,
    sector_stats: Optional[dict] = None,
    enabled_templates: Optional[list[str]] = None,
) -> dict:
    """
    Generate a complete article with 12 sections for a stock.

    Args:
        stock: dict with code, name, market, sector, rank, price, change, change_percent, volume, popularity_score
        snapshot_date: YYYY-MM-DD string
        sector_stats: optional sector aggregation data
        enabled_templates: optional list of template names to generate.
                         If None, all templates are generated (backward compatible).

    Returns:
        dict with keys: title, summary, rating, content_json
    """
    # Deterministic random per stock + date
    seed = f"{stock['code']}-{snapshot_date}"
    rng = random.Random(seed)

    # Dispatch table: template_name -> (generator_func, pass_sector_stats)
    # Some templates need sector_stats, most only need stock + rng
    dispatch = {
        "dragon_tiger": (generate_dragon_tiger, False),
        "abnormal_change": (generate_abnormal_change, False),
        "sector_correlation": (generate_sector_correlation, True),
        "fundamentals": (generate_fundamentals, False),
        "business": (generate_business_analysis, False),
        "subsidiaries": (generate_subsidiaries, False),
        "technical": (generate_technical, False),
        "fund_flow": (generate_fund_flow, False),
        "institutional": (generate_institutional, False),
        "announcements": (generate_announcements, False),
        "risk_warning": (generate_risk_warning, False),
        "ai_rating": (generate_ai_rating, True),  # needs content dict
    }

    # Determine which templates to run
    if enabled_templates is None:
        enabled = list(dispatch.keys())
    else:
        enabled = [t for t in enabled_templates if t in dispatch]

    # Generate sections dynamically
    content = {}
    for name in enabled:
        func, needs_extra = dispatch[name]
        if name == "sector_correlation":
            content[name] = func(stock, rng, sector_stats)
        elif name == "ai_rating":
            # ai_rating needs content dict - generate after others
            continue
        else:
            content[name] = func(stock, rng)

    # ai_rating depends on other content, generate last
    if "ai_rating" in enabled:
        content["ai_rating"] = generate_ai_rating(stock, content, rng)

    # Generate title and summary
    ai_rating = content.get("ai_rating", {})
    rating = ai_rating.get("rating", "hold")
    rating_label = ai_rating.get("rating_label", "观望")
    title = f"{stock['code']} {stock['name']} 深度分析报告 — {snapshot_date}"
    summary = generate_summary(stock, content, snapshot_date, rng)

    logger.info(f"Generated article for {stock['code']} {stock['name']}: rating={rating}")

    return {
        "title": title,
        "summary": summary,
        "rating": rating,
        "content_json": json.dumps(content, ensure_ascii=False),
    }


def generate_summary(stock: dict, content: dict, snapshot_date: str, rng: random.Random) -> str:
    """Generate a 150-200 character summary."""
    name = stock["name"]
    code = stock["code"]
    chg = stock.get("change_percent", 0) or 0
    direction = "上涨" if chg > 0 else ("下跌" if chg < 0 else "平盘")
    sector = stock.get("sector", "未分类")
    rating = content.get("ai_rating", {}).get("rating_label", "观望")
    vol = stock.get("volume", 0) or 0

    summaries = [
        f"{name}（{code}）今日{direction}{abs(chg):.2f}%，成交量{vol:.0f}手。"
        f"所属{sector}板块，当前处于市场关注度前列。"
        f"综合技术面、资金面和基本面分析，给予{rating}评级。",
        f"{name}（{code}）{snapshot_date}收盘{direction}{abs(chg):.2f}%，"
        f"当前股价{stock.get('price', 0):.2f}元。"
        f"技术面显示{'多头' if chg > 0 else '空头'}趋势，"
        f"资金流向{'净流入' if chg > 0 else '净流出'}，综合评级{rating}。",
        f"{name}（{code}）{direction}{abs(chg):.2f}%，"
        f"人气排名第{stock.get('rank', 0)}位。"
        f"所属{sector}板块整体{'走强' if chg > 0 else '走弱'}，"
        f"基本面指标{'良好' if chg > 0 else '需关注'}，建议{rating}。",
    ]

    return rng.choice(summaries)
